### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by 1232154pp4749687** [Nyumat/The-TikTok-Bot#6]
Syntax error found on Slenium v2 (autoViews.py)

submit = driver.find_element_by_xpath("//[@id="alternative"]/form/fieldset/div[2]/button").click()

![invalid syntax py](https://user-images.githubusercontent.com/18583466/90337719-3c8e9d80-dfdc-11ea-83c2-9b48a728c2f5.PNG)

**Comment by Nyumat** [comment]
Seen and taken care of. Pushing now.
